#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "$ROOT/scripts/lib.sh"

CALLER_UPSTREAM_OPENAI_BASE_URL_SET="${UPSTREAM_OPENAI_BASE_URL+x}"
CALLER_UPSTREAM_OPENAI_BASE_URL_VALUE="${UPSTREAM_OPENAI_BASE_URL-}"
CALLER_UPSTREAM_OPENAI_MODEL_SET="${UPSTREAM_OPENAI_MODEL+x}"
CALLER_UPSTREAM_OPENAI_MODEL_VALUE="${UPSTREAM_OPENAI_MODEL-}"
CALLER_UPSTREAM_API_KEY_SET="${UPSTREAM_API_KEY+x}"
CALLER_UPSTREAM_API_KEY_VALUE="${UPSTREAM_API_KEY-}"
CALLER_PROXY_PROVIDER_NAME_SET="${PROXY_PROVIDER_NAME+x}"
CALLER_PROXY_PROVIDER_NAME_VALUE="${PROXY_PROVIDER_NAME-}"
CALLER_PROXY_HOST_SET="${PROXY_HOST+x}"
CALLER_PROXY_HOST_VALUE="${PROXY_HOST-}"
CALLER_PROXY_PORT_SET="${PROXY_PORT+x}"
CALLER_PROXY_PORT_VALUE="${PROXY_PORT-}"
CALLER_PROXY_REQUEST_TIMEOUT_SET="${PROXY_REQUEST_TIMEOUT+x}"
CALLER_PROXY_REQUEST_TIMEOUT_VALUE="${PROXY_REQUEST_TIMEOUT-}"
CALLER_PROXY_STREAM_MODE_SET="${PROXY_STREAM_MODE+x}"
CALLER_PROXY_STREAM_MODE_VALUE="${PROXY_STREAM_MODE-}"
CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_SET="${PROXY_STREAM_HEARTBEAT_SECONDS+x}"
CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_VALUE="${PROXY_STREAM_HEARTBEAT_SECONDS-}"
CALLER_PROXY_TOOL_MODE_SET="${PROXY_TOOL_MODE+x}"
CALLER_PROXY_TOOL_MODE_VALUE="${PROXY_TOOL_MODE-}"

load_proxy_profile "$ROOT"

if [[ -n "$CALLER_UPSTREAM_OPENAI_BASE_URL_SET" ]]; then
  export UPSTREAM_OPENAI_BASE_URL="$CALLER_UPSTREAM_OPENAI_BASE_URL_VALUE"
fi
if [[ -n "$CALLER_UPSTREAM_OPENAI_MODEL_SET" ]]; then
  export UPSTREAM_OPENAI_MODEL="$CALLER_UPSTREAM_OPENAI_MODEL_VALUE"
fi
if [[ -n "$CALLER_UPSTREAM_API_KEY_SET" ]]; then
  export UPSTREAM_API_KEY="$CALLER_UPSTREAM_API_KEY_VALUE"
fi
if [[ -n "$CALLER_PROXY_PROVIDER_NAME_SET" ]]; then
  export PROXY_PROVIDER_NAME="$CALLER_PROXY_PROVIDER_NAME_VALUE"
fi
if [[ -n "$CALLER_PROXY_HOST_SET" ]]; then
  export PROXY_HOST="$CALLER_PROXY_HOST_VALUE"
fi
if [[ -n "$CALLER_PROXY_PORT_SET" ]]; then
  export PROXY_PORT="$CALLER_PROXY_PORT_VALUE"
fi
if [[ -n "$CALLER_PROXY_REQUEST_TIMEOUT_SET" ]]; then
  export PROXY_REQUEST_TIMEOUT="$CALLER_PROXY_REQUEST_TIMEOUT_VALUE"
fi
if [[ -n "$CALLER_PROXY_STREAM_MODE_SET" ]]; then
  export PROXY_STREAM_MODE="$CALLER_PROXY_STREAM_MODE_VALUE"
fi
if [[ -n "$CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_SET" ]]; then
  export PROXY_STREAM_HEARTBEAT_SECONDS="$CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_VALUE"
fi
if [[ -n "$CALLER_PROXY_TOOL_MODE_SET" ]]; then
  export PROXY_TOOL_MODE="$CALLER_PROXY_TOOL_MODE_VALUE"
fi

export UPSTREAM_OPENAI_BASE_URL="${UPSTREAM_OPENAI_BASE_URL:-${MTPLX_OPENAI_BASE_URL:-http://127.0.0.1:8030/v1}}"
export UPSTREAM_OPENAI_MODEL="${UPSTREAM_OPENAI_MODEL:-${MTPLX_OPENAI_MODEL:-mtplx-qwen36-27b-optimized-quality}}"
export UPSTREAM_API_KEY="${UPSTREAM_API_KEY:-${MTPLX_API_KEY:-local-mtplx}}"
export PROXY_PROVIDER_NAME="${PROXY_PROVIDER_NAME:-}"
export MTPLX_OPENAI_BASE_URL="${MTPLX_OPENAI_BASE_URL:-$UPSTREAM_OPENAI_BASE_URL}"
export MTPLX_OPENAI_MODEL="${MTPLX_OPENAI_MODEL:-$UPSTREAM_OPENAI_MODEL}"
export MTPLX_API_KEY="${MTPLX_API_KEY:-$UPSTREAM_API_KEY}"
export PROXY_HOST="${PROXY_HOST:-127.0.0.1}"
export PROXY_PORT="${PROXY_PORT:-18080}"
export PROXY_REQUEST_TIMEOUT="${PROXY_REQUEST_TIMEOUT:-240}"
export PROXY_MAX_TOKENS_CAP="${PROXY_MAX_TOKENS_CAP:-4096}"
export PROXY_UPSTREAM_RETRIES="${PROXY_UPSTREAM_RETRIES:-2}"
export PROXY_UPSTREAM_RETRY_DELAY="${PROXY_UPSTREAM_RETRY_DELAY:-2}"
export PROXY_STREAM_MODE="${PROXY_STREAM_MODE:-direct}"
export PROXY_STREAM_HEARTBEAT_SECONDS="${PROXY_STREAM_HEARTBEAT_SECONDS:-0}"
export PROXY_TOOL_MODE="${PROXY_TOOL_MODE:-pass}"
export PROXY_TOOL_ALLOWLIST="${PROXY_TOOL_ALLOWLIST:-}"
export PROXY_TOOL_VALIDATION="${PROXY_TOOL_VALIDATION:-schema}"
export PROXY_SCHEMA_LOG_PATH="${PROXY_SCHEMA_LOG_PATH:-}"
export PROXY_HARNESS_TOOLS="${PROXY_HARNESS_TOOLS:-submit_output}"
export PROXY_CLAUDE_SCIENCE_COMPAT="${PROXY_CLAUDE_SCIENCE_COMPAT:-0}"
export PROXY_MTPLX_AVOID_BACKGROUND_BYPASS="${PROXY_MTPLX_AVOID_BACKGROUND_BYPASS:-0}"
export PROXY_MTPLX_BACKGROUND_MAX_TOKENS="${PROXY_MTPLX_BACKGROUND_MAX_TOKENS:-48}"
export PROXY_MTPLX_BACKGROUND_NO_HISTORY_MAX_CHARS="${PROXY_MTPLX_BACKGROUND_NO_HISTORY_MAX_CHARS:-4096}"
export PROXY_ADVERTISED_MODELS="${PROXY_ADVERTISED_MODELS:-claude-opus-4-8,$UPSTREAM_OPENAI_MODEL}"
export PROXY_MODEL_DISPLAY_NAMES="${PROXY_MODEL_DISPLAY_NAMES:-}"

exec python3 "$ROOT/proxy/anthropic_mtplx_proxy.py" \
  --host "$PROXY_HOST" \
  --port "$PROXY_PORT" \
  --upstream-base "$UPSTREAM_OPENAI_BASE_URL" \
  --upstream-model "$UPSTREAM_OPENAI_MODEL" \
  --provider-name "$PROXY_PROVIDER_NAME" \
  --timeout "$PROXY_REQUEST_TIMEOUT" \
  --max-tokens-cap "$PROXY_MAX_TOKENS_CAP" \
  --upstream-retries "$PROXY_UPSTREAM_RETRIES" \
  --upstream-retry-delay "$PROXY_UPSTREAM_RETRY_DELAY" \
  --stream-mode "$PROXY_STREAM_MODE" \
  --stream-heartbeat-seconds "$PROXY_STREAM_HEARTBEAT_SECONDS" \
  --tool-mode "$PROXY_TOOL_MODE" \
  --tool-allowlist "$PROXY_TOOL_ALLOWLIST" \
  --tool-validation "$PROXY_TOOL_VALIDATION" \
  --schema-log-path "$PROXY_SCHEMA_LOG_PATH" \
  --harness-tools "$PROXY_HARNESS_TOOLS" \
  --claude-science-compat "$PROXY_CLAUDE_SCIENCE_COMPAT" \
  --mtplx-avoid-background-bypass "$PROXY_MTPLX_AVOID_BACKGROUND_BYPASS" \
  --mtplx-background-max-tokens "$PROXY_MTPLX_BACKGROUND_MAX_TOKENS" \
  --mtplx-background-no-history-max-chars "$PROXY_MTPLX_BACKGROUND_NO_HISTORY_MAX_CHARS" \
  --advertised-models "$PROXY_ADVERTISED_MODELS" \
  --model-display-names "$PROXY_MODEL_DISPLAY_NAMES"
