#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "$ROOT/scripts/lib.sh"

CALLER_UPSTREAM_OPENAI_BASE_URL_SET="${UPSTREAM_OPENAI_BASE_URL+x}"
CALLER_UPSTREAM_OPENAI_BASE_URL_VALUE="${UPSTREAM_OPENAI_BASE_URL-}"
CALLER_UPSTREAM_OPENAI_MODEL_SET="${UPSTREAM_OPENAI_MODEL+x}"
CALLER_UPSTREAM_OPENAI_MODEL_VALUE="${UPSTREAM_OPENAI_MODEL-}"
CALLER_UPSTREAM_API_KEY_SET="${UPSTREAM_API_KEY+x}"
CALLER_UPSTREAM_API_KEY_VALUE="${UPSTREAM_API_KEY-}"
CALLER_PROXY_PROVIDER_NAME_SET="${PROXY_PROVIDER_NAME+x}"
CALLER_PROXY_PROVIDER_NAME_VALUE="${PROXY_PROVIDER_NAME-}"
CALLER_PROXY_HOST_SET="${PROXY_HOST+x}"
CALLER_PROXY_HOST_VALUE="${PROXY_HOST-}"
CALLER_PROXY_PORT_SET="${PROXY_PORT+x}"
CALLER_PROXY_PORT_VALUE="${PROXY_PORT-}"
CALLER_PROXY_REQUEST_TIMEOUT_SET="${PROXY_REQUEST_TIMEOUT+x}"
CALLER_PROXY_REQUEST_TIMEOUT_VALUE="${PROXY_REQUEST_TIMEOUT-}"
CALLER_PROXY_STREAM_MODE_SET="${PROXY_STREAM_MODE+x}"
CALLER_PROXY_STREAM_MODE_VALUE="${PROXY_STREAM_MODE-}"
CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_SET="${PROXY_STREAM_HEARTBEAT_SECONDS+x}"
CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_VALUE="${PROXY_STREAM_HEARTBEAT_SECONDS-}"
CALLER_PROXY_TOOL_MODE_SET="${PROXY_TOOL_MODE+x}"
CALLER_PROXY_TOOL_MODE_VALUE="${PROXY_TOOL_MODE-}"
CALLER_PROXY_STRIP_THINKING_TEXT_SET="${PROXY_STRIP_THINKING_TEXT+x}"
CALLER_PROXY_STRIP_THINKING_TEXT_VALUE="${PROXY_STRIP_THINKING_TEXT-}"
CALLER_PROXY_SERVER_WEB_SEARCH_SET="${PROXY_SERVER_WEB_SEARCH+x}"
CALLER_PROXY_SERVER_WEB_SEARCH_VALUE="${PROXY_SERVER_WEB_SEARCH-}"
CALLER_PROXY_SERVER_WEB_SEARCH_MAX_RESULTS_SET="${PROXY_SERVER_WEB_SEARCH_MAX_RESULTS+x}"
CALLER_PROXY_SERVER_WEB_SEARCH_MAX_RESULTS_VALUE="${PROXY_SERVER_WEB_SEARCH_MAX_RESULTS-}"
CALLER_PROXY_SERVER_WEB_SEARCH_MAX_USES_SET="${PROXY_SERVER_WEB_SEARCH_MAX_USES+x}"
CALLER_PROXY_SERVER_WEB_SEARCH_MAX_USES_VALUE="${PROXY_SERVER_WEB_SEARCH_MAX_USES-}"
CALLER_PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES_SET="${PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES+x}"
CALLER_PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES_VALUE="${PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES-}"
CALLER_TAVILY_API_KEY_SET="${TAVILY_API_KEY+x}"
CALLER_TAVILY_API_KEY_VALUE="${TAVILY_API_KEY-}"
CALLER_TAVILY_BASE_URL_SET="${TAVILY_BASE_URL+x}"
CALLER_TAVILY_BASE_URL_VALUE="${TAVILY_BASE_URL-}"
CALLER_FIRECRAWL_API_KEY_SET="${FIRECRAWL_API_KEY+x}"
CALLER_FIRECRAWL_API_KEY_VALUE="${FIRECRAWL_API_KEY-}"
CALLER_FIRECRAWL_BASE_URL_SET="${FIRECRAWL_BASE_URL+x}"
CALLER_FIRECRAWL_BASE_URL_VALUE="${FIRECRAWL_BASE_URL-}"

load_proxy_profile "$ROOT"

LOCAL_PROXY_ENV="${PROXY_EXTRA_ENV_FILE:-$ROOT/_local/proxy.env}"
if [[ -f "$LOCAL_PROXY_ENV" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$LOCAL_PROXY_ENV"
  set +a
elif [[ -f "$ROOT/_local/firecrawl.env" ]]; then
  set -a
  # Backward-compatible local fallback from early Firecrawl bridge testing.
  # shellcheck disable=SC1090
  source "$ROOT/_local/firecrawl.env"
  set +a
fi

if [[ -n "$CALLER_UPSTREAM_OPENAI_BASE_URL_SET" ]]; then
  export UPSTREAM_OPENAI_BASE_URL="$CALLER_UPSTREAM_OPENAI_BASE_URL_VALUE"
fi
if [[ -n "$CALLER_UPSTREAM_OPENAI_MODEL_SET" ]]; then
  export UPSTREAM_OPENAI_MODEL="$CALLER_UPSTREAM_OPENAI_MODEL_VALUE"
fi
if [[ -n "$CALLER_UPSTREAM_API_KEY_SET" ]]; then
  export UPSTREAM_API_KEY="$CALLER_UPSTREAM_API_KEY_VALUE"
fi
if [[ -n "$CALLER_PROXY_PROVIDER_NAME_SET" ]]; then
  export PROXY_PROVIDER_NAME="$CALLER_PROXY_PROVIDER_NAME_VALUE"
fi
if [[ -n "$CALLER_PROXY_HOST_SET" ]]; then
  export PROXY_HOST="$CALLER_PROXY_HOST_VALUE"
fi
if [[ -n "$CALLER_PROXY_PORT_SET" ]]; then
  export PROXY_PORT="$CALLER_PROXY_PORT_VALUE"
fi
if [[ -n "$CALLER_PROXY_REQUEST_TIMEOUT_SET" ]]; then
  export PROXY_REQUEST_TIMEOUT="$CALLER_PROXY_REQUEST_TIMEOUT_VALUE"
fi
if [[ -n "$CALLER_PROXY_STREAM_MODE_SET" ]]; then
  export PROXY_STREAM_MODE="$CALLER_PROXY_STREAM_MODE_VALUE"
fi
if [[ -n "$CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_SET" ]]; then
  export PROXY_STREAM_HEARTBEAT_SECONDS="$CALLER_PROXY_STREAM_HEARTBEAT_SECONDS_VALUE"
fi
if [[ -n "$CALLER_PROXY_TOOL_MODE_SET" ]]; then
  export PROXY_TOOL_MODE="$CALLER_PROXY_TOOL_MODE_VALUE"
fi
if [[ -n "$CALLER_PROXY_STRIP_THINKING_TEXT_SET" ]]; then
  export PROXY_STRIP_THINKING_TEXT="$CALLER_PROXY_STRIP_THINKING_TEXT_VALUE"
fi
if [[ -n "$CALLER_PROXY_SERVER_WEB_SEARCH_SET" ]]; then
  export PROXY_SERVER_WEB_SEARCH="$CALLER_PROXY_SERVER_WEB_SEARCH_VALUE"
fi
if [[ -n "$CALLER_PROXY_SERVER_WEB_SEARCH_MAX_RESULTS_SET" ]]; then
  export PROXY_SERVER_WEB_SEARCH_MAX_RESULTS="$CALLER_PROXY_SERVER_WEB_SEARCH_MAX_RESULTS_VALUE"
fi
if [[ -n "$CALLER_PROXY_SERVER_WEB_SEARCH_MAX_USES_SET" ]]; then
  export PROXY_SERVER_WEB_SEARCH_MAX_USES="$CALLER_PROXY_SERVER_WEB_SEARCH_MAX_USES_VALUE"
fi
if [[ -n "$CALLER_PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES_SET" ]]; then
  export PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES="$CALLER_PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES_VALUE"
fi
if [[ -n "$CALLER_TAVILY_API_KEY_SET" ]]; then
  export TAVILY_API_KEY="$CALLER_TAVILY_API_KEY_VALUE"
fi
if [[ -n "$CALLER_TAVILY_BASE_URL_SET" ]]; then
  export TAVILY_BASE_URL="$CALLER_TAVILY_BASE_URL_VALUE"
fi
if [[ -n "$CALLER_FIRECRAWL_API_KEY_SET" ]]; then
  export FIRECRAWL_API_KEY="$CALLER_FIRECRAWL_API_KEY_VALUE"
fi
if [[ -n "$CALLER_FIRECRAWL_BASE_URL_SET" ]]; then
  export FIRECRAWL_BASE_URL="$CALLER_FIRECRAWL_BASE_URL_VALUE"
fi

export UPSTREAM_OPENAI_BASE_URL="${UPSTREAM_OPENAI_BASE_URL:-${MTPLX_OPENAI_BASE_URL:-http://127.0.0.1:8030/v1}}"
export UPSTREAM_OPENAI_MODEL="${UPSTREAM_OPENAI_MODEL:-${MTPLX_OPENAI_MODEL:-mtplx-qwen36-27b-optimized-quality}}"
export UPSTREAM_API_KEY="${UPSTREAM_API_KEY:-${MTPLX_API_KEY:-local-mtplx}}"
export PROXY_PROVIDER_NAME="${PROXY_PROVIDER_NAME:-}"
export MTPLX_OPENAI_BASE_URL="${MTPLX_OPENAI_BASE_URL:-$UPSTREAM_OPENAI_BASE_URL}"
export MTPLX_OPENAI_MODEL="${MTPLX_OPENAI_MODEL:-$UPSTREAM_OPENAI_MODEL}"
export MTPLX_API_KEY="${MTPLX_API_KEY:-$UPSTREAM_API_KEY}"
export PROXY_HOST="${PROXY_HOST:-127.0.0.1}"
export PROXY_PORT="${PROXY_PORT:-18080}"
export PROXY_REQUEST_TIMEOUT="${PROXY_REQUEST_TIMEOUT:-240}"
export PROXY_MAX_TOKENS_CAP="${PROXY_MAX_TOKENS_CAP:-4096}"
export PROXY_UPSTREAM_RETRIES="${PROXY_UPSTREAM_RETRIES:-2}"
export PROXY_UPSTREAM_RETRY_DELAY="${PROXY_UPSTREAM_RETRY_DELAY:-2}"
export PROXY_STREAM_MODE="${PROXY_STREAM_MODE:-direct}"
export PROXY_STREAM_HEARTBEAT_SECONDS="${PROXY_STREAM_HEARTBEAT_SECONDS:-0}"
export PROXY_TOOL_MODE="${PROXY_TOOL_MODE:-pass}"
export PROXY_TOOL_VALIDATION="${PROXY_TOOL_VALIDATION:-schema}"
export PROXY_TOOL_REPAIR="${PROXY_TOOL_REPAIR:-metadata}"
export PROXY_FORCE_MENTIONED_TOOL="${PROXY_FORCE_MENTIONED_TOOL:-0}"
export PROXY_PARSE_TEXT_TOOL_CALLS="${PROXY_PARSE_TEXT_TOOL_CALLS:-0}"
export PROXY_STRIP_THINKING_TEXT="${PROXY_STRIP_THINKING_TEXT:-0}"
export PROXY_SCHEMA_LOG_PATH="${PROXY_SCHEMA_LOG_PATH:-}"
export PROXY_REQUEST_SHAPE_LOG_PATH="${PROXY_REQUEST_SHAPE_LOG_PATH:-}"
export PROXY_RAW_REQUEST_CAPTURE_DIR="${PROXY_RAW_REQUEST_CAPTURE_DIR:-}"
export PROXY_HARNESS_TOOLS="${PROXY_HARNESS_TOOLS:-submit_output}"
export PROXY_CLAUDE_SCIENCE_COMPAT="${PROXY_CLAUDE_SCIENCE_COMPAT:-0}"
export PROXY_SERVER_WEB_SEARCH="${PROXY_SERVER_WEB_SEARCH:-off}"
export PROXY_SERVER_WEB_SEARCH_MAX_RESULTS="${PROXY_SERVER_WEB_SEARCH_MAX_RESULTS:-5}"
export PROXY_SERVER_WEB_SEARCH_MAX_USES="${PROXY_SERVER_WEB_SEARCH_MAX_USES:-3}"
export PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES="${PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES:-$PROXY_SERVER_WEB_SEARCH_MAX_USES}"
export TAVILY_API_KEY="${TAVILY_API_KEY:-}"
export TAVILY_BASE_URL="${TAVILY_BASE_URL:-https://api.tavily.com}"
export FIRECRAWL_API_KEY="${FIRECRAWL_API_KEY:-}"
export FIRECRAWL_BASE_URL="${FIRECRAWL_BASE_URL:-https://api.firecrawl.dev}"
export PROXY_MTPLX_AVOID_BACKGROUND_BYPASS="${PROXY_MTPLX_AVOID_BACKGROUND_BYPASS:-0}"
export PROXY_MTPLX_BACKGROUND_MAX_TOKENS="${PROXY_MTPLX_BACKGROUND_MAX_TOKENS:-48}"
export PROXY_MTPLX_BACKGROUND_NO_HISTORY_MAX_CHARS="${PROXY_MTPLX_BACKGROUND_NO_HISTORY_MAX_CHARS:-4096}"
export PROXY_ADVERTISED_MODELS="${PROXY_ADVERTISED_MODELS:-claude-opus-4-8,$UPSTREAM_OPENAI_MODEL}"
export PROXY_MODEL_DISPLAY_NAMES="${PROXY_MODEL_DISPLAY_NAMES:-}"

exec python3 "$ROOT/proxy/anthropic_mtplx_proxy.py" \
  --host "$PROXY_HOST" \
  --port "$PROXY_PORT" \
  --upstream-base "$UPSTREAM_OPENAI_BASE_URL" \
  --upstream-model "$UPSTREAM_OPENAI_MODEL" \
  --provider-name "$PROXY_PROVIDER_NAME" \
  --timeout "$PROXY_REQUEST_TIMEOUT" \
  --max-tokens-cap "$PROXY_MAX_TOKENS_CAP" \
  --upstream-retries "$PROXY_UPSTREAM_RETRIES" \
  --upstream-retry-delay "$PROXY_UPSTREAM_RETRY_DELAY" \
  --stream-mode "$PROXY_STREAM_MODE" \
  --stream-heartbeat-seconds "$PROXY_STREAM_HEARTBEAT_SECONDS" \
  --tool-mode "$PROXY_TOOL_MODE" \
  --tool-validation "$PROXY_TOOL_VALIDATION" \
  --tool-repair "$PROXY_TOOL_REPAIR" \
  --force-mentioned-tool "$PROXY_FORCE_MENTIONED_TOOL" \
  --parse-text-tool-calls "$PROXY_PARSE_TEXT_TOOL_CALLS" \
  --strip-thinking-text "$PROXY_STRIP_THINKING_TEXT" \
  --schema-log-path "$PROXY_SCHEMA_LOG_PATH" \
  --request-shape-log-path "$PROXY_REQUEST_SHAPE_LOG_PATH" \
  --raw-request-capture-dir "$PROXY_RAW_REQUEST_CAPTURE_DIR" \
  --harness-tools "$PROXY_HARNESS_TOOLS" \
  --claude-science-compat "$PROXY_CLAUDE_SCIENCE_COMPAT" \
  --server-web-search "$PROXY_SERVER_WEB_SEARCH" \
  --server-web-search-max-results "$PROXY_SERVER_WEB_SEARCH_MAX_RESULTS" \
  --server-web-search-max-uses "$PROXY_SERVER_WEB_SEARCH_MAX_USES" \
  --server-web-search-conversation-max-uses "$PROXY_SERVER_WEB_SEARCH_CONVERSATION_MAX_USES" \
  --tavily-base-url "$TAVILY_BASE_URL" \
  --firecrawl-base-url "$FIRECRAWL_BASE_URL" \
  --mtplx-avoid-background-bypass "$PROXY_MTPLX_AVOID_BACKGROUND_BYPASS" \
  --mtplx-background-max-tokens "$PROXY_MTPLX_BACKGROUND_MAX_TOKENS" \
  --mtplx-background-no-history-max-chars "$PROXY_MTPLX_BACKGROUND_NO_HISTORY_MAX_CHARS" \
  --advertised-models "$PROXY_ADVERTISED_MODELS" \
  --model-display-names "$PROXY_MODEL_DISPLAY_NAMES"
